hpp: # (2)
  # Head on collisions
  '0101': '1010'
  '1010': '0101'
fhpi: # (5)
  # Head on collisions (3)
  '001001': [ '010010', '100100' ]
  '010010': [ '100100', '001001' ]
  '100100': [ '001001', '010010' ]
  # Three particles (Mercedes collisions) (2)
  '010101': '101010'
  '101010': '010101'
fhpii: # (22)
  # FHP I collisions (5)
  '001001': [ '010010', '100100' ]
  '010010': [ '100100', '001001' ]
  '100100': [ '001001', '010010' ]
  '010101': '101010'
  '101010': '010101'

  # Create rest particle (6)
  '0000101': '1000010'
  '0001010': '1000100'
  '0010100': '1001000'
  '0101000': '1010000'
  '0010001': '1100000'
  '0100010': '1000001'

  # Destroy rest particle (6)
  '1010000': '0101000'
  '1100000': '0010001'
  '1000001': '0100010'
  '1000010': '0000101'
  '1000100': '0001010'
  '1001000': '0010100'

  # FHP I collisions with rest particle (5)
  '1001001': [ '1010010', '1100100' ]
  '1010010': [ '1100100', '1001001' ]
  '1100100': [ '1001001', '1010010' ]
  '1010101': '1101010'
  '1101010': '1010101'
fhpiii: # (76)
  # FHP II collisions (22)
  '001001': [ '010010', '100100' ]
  '010010': [ '100100', '001001' ]
  '100100': [ '001001', '010010' ]
  '010101': '101010'
  '101010': '010101'

  '0000101': '1000010'
  '0001010': '1000100'
  '0010100': '1001000'
  '0101000': '1010000'
  '0010001': '1100000'
  '0100010': '1000001'

  '1010000': '0101000'
  '1100000': '0010001'
  '1000001': '0100010'
  '1000010': '0000101'
  '1000100': '0001010'
  '1001000': '0010100'

  '1001001': [ '1010010', '1100100' ]
  '1010010': [ '1100100', '1001001' ]
  '1100100': [ '1001001', '1010010' ]
  '1010101': '1101010'
  '1101010': '1010101'
