hpp: # (2) 4 bits
  # Head on collisions (2)
  '0101': '1010'
  '1010': '0101'
fhp_i: # (5) 6 bits
  # Head on collisions (3)
  '001001': [ '010010', '100100' ]
  '010010': [ '100100', '001001' ]
  '100100': [ '001001', '010010' ]
  # Three particles (Mercedes collisions) (2)
  '010101': '101010'
  '101010': '010101'
fhp_ii: # (22) 7 bits
  # FHP I collisions (5)
  '0001001': [ '0010010', '0100100' ]
  '0010010': [ '0100100', '0001001' ]
  '0100100': [ '0001001', '0010010' ]
  '0010101': '0101010'
  '0101010': '0010101'

  # Create rest particle (6)
  '0100010': '1000001'
  '0000101': '1000010'
  '0001010': '1000100'
  '0010100': '1001000'
  '0101000': '1010000'
  '0010001': '1100000'

  # Destroy rest particle (6)
  '1000001': '0100010'
  '1000010': '0000101'
  '1000100': '0001010'
  '1001000': '0010100'
  '1010000': '0101000'
  '1100000': '0010001'

  # FHP I collisions with rest particle (5)
  '1001001': [ '1010010', '1100100' ]
  '1010010': [ '1100100', '1001001' ]
  '1100100': [ '1001001', '1010010' ]
  '1010101': '1101010'
  '1101010': '1010101'

fhp_iii: # (76) 7 bits
  '0001001': [ '0010010', '0100100' ] # 2p
  '0010010': [ '0100100', '0001001' ] # 2p
  '0100100': [ '0001001', '0010010' ] # 2p
  '0010101': '0101010' # 3 p
  '0101010': '0010101' # 3 p
  '0000101': '1000010' # 2p
  '0001010': '1000100' # 2p
  '0010100': '1001000' # 2p
  '0101000': '1010000' # 2p
  '0010001': '1100000' # 2p
  '0100010': '1000001' # 2p
  '1010000': '0101000' # 2p
  '1100000': '0010001' # 2p
  '1000001': '0100010' # 2p
  '1000010': '0000101' # 2p
  '1000100': '0001010' # 2p
  '1001000': '0010100' # 2p
  '1001001': [ '1010010', '1100100' ]  # 3 p
  '1010010': [ '1100100', '1001001' ]  # 3 p
  '1100100': [ '1001001', '1010010' ]  # 3 p
  '1010101': '1101010' # 4p
  '1101010': '1010101' # 4p
  '0101100': [ '0011010', '1010100' ] # COLLISION # FHP III specific 3 particles collisions (18) # 3 regular particles (12)
  '0011001': [ '0110100', '1101000' ] # COLLISION
  '0110010': [ '0101001', '1010001' ] # COLLISION
  '0100101': [ '0010011', '1100010' ] # COLLISION
  '0001011': [ '0100110', '1000101' ] # COLLISION
  '0010110': [ '0001101', '1001010' ] # COLLISION
  '0100110': [ '0001011', '1000101' ] # COLLISION
  '0001101': [ '0010110', '1001010' ] # COLLISION
  '0011010': [ '0101100', '1010100' ] # COLLISION
  '0110100': [ '0011001', '1101000' ] # COLLISION
  '0101001': [ '0110010', '1010001' ] # COLLISION
  '0010011': [ '0100101', '1100010' ] # COLLISION
  '1000101': [ '0001011', '0100110' ] # COLLISION 69 # 2 regular and 1 rest particle (6)
  '1001010': [ '0010110', '0001101' ] # COLLISION 74
  '1010001': [ '0101001', '0110010' ] # COLLISION 81
  '1010100': [ '0101100', '0011010' ] # COLLISION 84
  '1100010': [ '0100101', '0010011' ] # COLLISION 98
  '1101000': [ '0011001', '0110100' ] # COLLISION 104
  '1001011': [ '0010111', '1100110' ] # 75 - (23, 102) # FHP III specific 4 particles collisions (23)
  '0010111': [ '1100110', '1001011' ] # 23 - (102, 75)
  '1100110': [ '1001011', '0010111' ] # 102 - (75, 23)
  '1001101': [ '1010110', '0101110' ] # 77 - (86, 46)
  '1010110': [ '0101110', '1001101' ] # 86 - (46, 77)
  '0101110': [ '1001101', '1010110' ] # 46 - (77, 86)
  '1010011': [ '1100101', '0101011' ] # 83 - (101, 43)
  '1100101': [ '0101011', '1010011' ] # 101 - (43, 83)
  '0101011': [ '1010011', '1100101' ] # 43 - (83, 101)
  '1110010': [ '0110101', '1101001' ] # 114 - (53, 105)
  '0110101': [ '1101001', '1110010' ] # 53 - (105, 114
  '1101001': [ '1110010', '0110101' ] # 105 - (114, 53)
  '1110100': [ '1011001', '0111010' ] # 116 - (89, 58)
  '1011001': [ '0111010', '1110100' ] # 89 - (58, 116)
  '0111010': [ '1110100', '1011001' ] # 58 - (116, 89)
  '1011010': [ '1101100', '0011101' ] # 90 - (108, 29)
  '1101100': [ '0011101', '1011010' ] # 108 - (29, 90)
  '0011101': [ '1011010', '1101100' ] # 29 - (90, 108)
  '0011011': [ '0101101', '0110110' ] # 27 - (45, 54)
  '0101101': [ '0110110', '0011011' ] # 45 - (54, 27)
  '0110110': [ '0011011', '0101101' ] # 54 - (27, 45)
  '0011111': '1101110' # 31 - 110 # 5part one off star
  '0111110': '1011101' # 62 -  93
  '0111101': '1111010' # 61 - 122
  '0111011': '1110101' # 59 - 117
  '0110111': '1101011' # 55 - 107
  '0101111': '1010111' # 47 -  87
  '1101110': '0011111' # 110 - 31 # reversed to one off star
  '1011101': '0111110' #  93 - 62
  '1111010': '0111101' # 122 - 61
  '1110101': '0111011' # 117 - 59
  '1101011': '0110111' # 107 - 55
  '1010111': '0101111' #  87 - 47
  '1011011': [ '1101101', '1110110' ] #  91 - (109, 118) # X shape with a rest particle (3 in circle)
  '1101101': [ '1110110', '1011011' ] # 109 - (118,  91)
  '1110110': [ '1011011', '1101101' ] # 118 - ( 91, 109)

  # 73/76

  # [X] 3 particle 23
  # [ ] 4 particle 23
  # [X] 5 particle 15
