fhp_6bits:
  # 0 bits (1)
  '000000': '#000000'

  # 1 bits (6)
  '000001': '#2D2D2D'
  '000010': '#2D2D2D'
  '000100': '#2D2D2D'
  '001000': '#2D2D2D'
  '010000': '#2D2D2D'
  '100000': '#2D2D2D'

  # 2 bits (15)
  '000011': '#575757'
  '000101': '#575757'
  '000110': '#575757'
  '001001': '#575757'
  '001010': '#575757'
  '001100': '#575757'
  '010001': '#575757'
  '010010': '#575757'
  '010100': '#575757'
  '100001': '#575757'
  '100010': '#575757'
  '100100': '#575757'
  '011000': '#575757'
  '101000': '#575757'
  '110000': '#575757'

  # 3 bits (20)
  '000111': '#818181'
  '001011': '#818181'
  '001101': '#818181'
  '001110': '#818181'
  '010011': '#818181'
  '010101': '#818181'
  '010110': '#818181'
  '011001': '#818181'
  '011010': '#818181'
  '011100': '#818181'
  '100011': '#818181'
  '111000': '#818181'
  '100101': '#818181'
  '110010': '#818181'
  '100110': '#818181'
  '101100': '#818181'
  '110001': '#818181'
  '101001': '#818181'
  '101010': '#818181'
  '110100': '#818181'

  # 4 bits (15)
  '001111': '#ABABAB'
  '011011': '#ABABAB'
  '011101': '#ABABAB'
  '011110': '#ABABAB'
  '100111': '#ABABAB'
  '101011': '#ABABAB'
  '101101': '#ABABAB'
  '101110': '#ABABAB'
  '110011': '#ABABAB'
  '110101': '#ABABAB'
  '110110': '#ABABAB'
  '111001': '#ABABAB'
  '111010': '#ABABAB'
  '111100': '#ABABAB'
  '010111': '#ABABAB'

  # 5 bits (6)
  '111110': '#D5D5D5'
  '111101': '#D5D5D5'
  '111011': '#D5D5D5'
  '110111': '#D5D5D5'
  '101111': '#D5D5D5'
  '011111': '#D5D5D5'

  # 6 bits (1)
  '111111': '#FFFFFF'

fhp_7bits:
  # 0 bits (1)
  '000000': '#000000'

  # 1 bits (6)
  '000001': '#2D2D2D'
  '000010': '#2D2D2D'
  '000100': '#2D2D2D'
  '001000': '#2D2D2D'
  '010000': '#2D2D2D'
  '100000': '#2D2D2D'

  # 2 bits (15)
  '000011': '#575757'
  '000101': '#575757'
  '000110': '#575757'
  '001001': '#575757'
  '001010': '#575757'
  '001100': '#575757'
  '010001': '#575757'
  '010010': '#575757'
  '010100': '#575757'
  '100001': '#575757'
  '100010': '#575757'
  '100100': '#575757'
  '011000': '#575757'
  '101000': '#575757'
  '110000': '#575757'

  # 3 bits (20)
  '000111': '#818181'
  '001011': '#818181'
  '001101': '#818181'
  '001110': '#818181'
  '010011': '#818181'
  '010101': '#818181'
  '010110': '#818181'
  '011001': '#818181'
  '011010': '#818181'
  '011100': '#818181'
  '100011': '#818181'
  '111000': '#818181'
  '100101': '#818181'
  '110010': '#818181'
  '100110': '#818181'
  '101100': '#818181'
  '110001': '#818181'
  '101001': '#818181'
  '101010': '#818181'
  '110100': '#818181'

  # 4 bits (15)
  '001111': '#ABABAB'
  '011011': '#ABABAB'
  '011101': '#ABABAB'
  '011110': '#ABABAB'
  '100111': '#ABABAB'
  '101011': '#ABABAB'
  '101101': '#ABABAB'
  '101110': '#ABABAB'
  '110011': '#ABABAB'
  '110101': '#ABABAB'
  '110110': '#ABABAB'
  '111001': '#ABABAB'
  '111010': '#ABABAB'
  '111100': '#ABABAB'
  '010111': '#ABABAB'

  # 5 bits (6)
  '111110': '#D5D5D5'
  '111101': '#D5D5D5'
  '111011': '#D5D5D5'
  '110111': '#D5D5D5'
  '101111': '#D5D5D5'
  '011111': '#D5D5D5'

  # 6 bits (1)
  '111111': '#FFFFFF'