particle:
  '1101000': '1101000'
  '1001010': '1001010'
  '1010001': '1010001'
  '1010100': '1010100'
  '1000101': '1000101'
  '1100010': '1100010'
  '1000000': '1000000'
  '0000000': '0000000'
  '0000001': '0000001'
  '0000010': '0000010'
  '0000100': '0000100'
  '0000011': '0000011'
  '0000101': '1000010' # COLLISION - create rest particle
  '0001010': '1000100' # ^^
  '0010100': '1001000' # ^^
  '0101000': '1010000' # ^^
  '0010001': '1100000' # ^^
  '0100010': '1000001' # ^^
  '1000001': '0100010' # COLLISION - destroy rest particle
  '1000010': '0000101' # ^^
  '1000100': '0001010' # ^^
  '1001000': '0010100' # ^^
  '1100000': '0010001' # ^^
  '1010000': '0101000' # ^^
  '0000110': '0000110'
  '0000111': '0000111'
  '0001000': '0001000'
  '0001001': [ '0010010', '0100100' ] # COLLISION
  '0001011': '0001011'
  '0001100': '0001100'
  '0001101': '0001101'
  '0001110': '0001110'
  '0001111': '0001111'
  '0010000': '0010000'
  '0010010': [ '0100100', '0001001' ] # COLLISION
  '0010011': '0010011'
  '0010101': '0101010' # COLLISION
  '0010110': '0010110'
  '0010111': '0010111'
  '0011000': '0011000'
  '0011001': '0011001'
  '0011010': '0011010'
  '0011011': '0011011'
  '0011100': '0011100'
  '0011101': '0011101'
  '0011110': '0011110'
  '0011111': '0011111'
  '0100000': '0100000'
  '0100001': '0100001'
  '0100011': '0100011'
  '0100100': [ '0001001', '0010010' ] # COLLISION
  '0100101': '0100101'
  '0100110': '0100110'
  '0100111': '0100111'
  '0101001': '0101001'
  '0101010': '0010101' # COLLISION
  '0101011': '0101011'
  '0101100': '0101100'
  '0101101': '0101101'
  '0101110': '0101110'
  '0101111': '0101111'
  '0110000': '0110000'
  '0110001': '0110001'
  '0110010': '0110010'
  '0110011': '0110011'
  '0110100': '0110100'
  '0110101': '0110101'
  '0110110': '0110110'
  '0110111': '0110111'
  '0111000': '0111000'
  '0111001': '0111001'
  '0111010': '0111010'
  '0111011': '0111011'
  '0111100': '0111100'
  '0111101': '0111101'
  '0111110': '0111110'
  '0111111': '0111111'
  '1000011': '1000011'
  '1000110': '1000110'
  '1000111': '1000111'
  '1001001': [ '1010010', '1100100' ] # COLLISION
  '1001011': '1001011'
  '1001100': '1001100'
  '1001101': '1001101'
  '1001110': '1001110'
  '1001111': '1001111'
  '1010010': [ '1100100', '1001001' ] # COLLISION
  '1010011': '1010011'
  '1010101': '1101010' # COLLISION
  '1010110': '1010110'
  '1010111': '1010111'
  '1011000': '1011000'
  '1011001': '1011001'
  '1011010': '1011010'
  '1011011': '1011011'
  '1011100': '1011100'
  '1011101': '1011101'
  '1011110': '1011110'
  '1011111': '1011111'
  '1100001': '1100001'
  '1100011': '1100011'
  '1100100': [ '1001001', '1010010' ] # COLLISION
  '1100101': '1100101'
  '1100110': '1100110'
  '1100111': '1100111'
  '1101001': '1101001'
  '1101010': '1010101' # COLLISION
  '1101011': '1101011'
  '1101100': '1101100'
  '1101101': '1101101'
  '1101110': '1101110'
  '1101111': '1101111'
  '1110000': '1110000'
  '1110001': '1110001'
  '1110010': '1110010'
  '1110011': '1110011'
  '1110100': '1110100'
  '1110101': '1110101'
  '1110110': '1110110'
  '1110111': '1110111'
  '1111000': '1111000'
  '1111001': '1111001'
  '1111010': '1111010'
  '1111011': '1111011'
  '1111100': '1111100'
  '1111101': '1111101'
  '1111110': '1111110'
  '1111111': '1111111'

obstacle:
  # number of bits: 0, count: 1
  '10000000': '10000000'
  # number of bits: 1, count: 6
  '10000001': '10001000'
  '10000010': '10010000'
  '10000100': '10100000'
  '10001000': '10000001'
  '10010000': '10000010'
  '10100000': '10000100'
  # number of bits: 2, count: 15
  '10000011': '10011000'
  '10000101': '10101000'
  '10000110': '10110000'
  '10001001': '10001001'
  '10001010': '10010001'
  '10001100': '10100001'
  '10010100': '10100010'
  '10010010': '10010010'
  '10010001': '10001010'
  '10100001': '10001100'
  '10011000': '10000011'
  '10100010': '10010100'
  '10100100': '10100100'
  '10110000': '10000110'
  '10101000': '10000101'
  # number of bits: 3, count: 20
  '10000111': '10111000'
  '10001011': '10011001'
  '10001101': '10101001'
  '10001110': '10110001'
  '10010011': '10011010'
  '10010101': '10101010'
  '10011010': '10010011'
  '10011001': '10001011'
  '10100011': '10011100'
  '10100110': '10110100'
  '10011100': '10100011'
  '10100101': '10101100'
  '10101001': '10001101'
  '10101010': '10010101'
  '10110001': '10001110'
  '10110010': '10010110'
  '10110100': '10100110'
  '10111000': '10000111'
  '10101100': '10100101'
  '10010110': '10110010'
  # number of bits: 4, count: 15
  '10100111': '10111100'
  '10101011': '10011101'
  '10011011': '10011011'
  '10001111': '10111001'
  '10010111': '10111010'
  '10011110': '10110011'
  '10011101': '10101011'
  '10101101': '10101101'
  '10110011': '10011110'
  '10110101': '10101110'
  '10101110': '10110101'
  '10110110': '10110110'
  '10111001': '10001111'
  '10111010': '10010111'
  '10111100': '10100111'
  # number of bits: 5, count: 6
  '10011111': '10111011'
  '10101111': '10111101'
  '10110111': '10111110'
  '10111101': '10101111'
  '10111011': '10011111'
  '10111110': '10110111'
  # number of bits: 6, count: 1
  '10111111': '10111111'
